// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cslkwjmedllngixuhcrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbGt3am1lZGxsbmdpeHVoY3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzE5MzAsImV4cCI6MjA2OTA0NzkzMH0.vP2MhWIol_arEIBVQV8BFZ3CJ5QT8r06V9w1e5BSnV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});